// <auto-generated />
namespace testing_app.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class passwordinserted : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(passwordinserted));
        
        string IMigrationMetadata.Id
        {
            get { return "202205130527213_passwordinserted"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
