// <auto-generated />
namespace testing_app.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class confirmPasswordChanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(confirmPasswordChanged));
        
        string IMigrationMetadata.Id
        {
            get { return "202205180459001_confirmPasswordChanged"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
